apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: items-dev-295212               # Real ID of the project
  artifacts:
    - image: us.gcr.io/items-dev-295212/auth  # us.gcr.io/project/folder-name
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .